services:
  # Service: Chatbot FastAPI
  chatbot:
    build: .
    container_name: chatbot-nasikotak
    ports:
      - "127.0.0.1:8001:8001"  # Hanya akses internal (diakses via Nginx)
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - LLM_BASE_URL=${LLM_BASE_URL}
      - NINEROUTER_API_KEY=${NINEROUTER_API_KEY}
    volumes:
      - ./data:/app/data
      - ./knowledge_base:/app/knowledge_base
      - ./faiss_index:/app/faiss_index
      - ./.hf_cache:/home/appuser/.cache/huggingface
